name: btc_address_validate
version: 1.2.0
description: A minimal library to validate Bitcoin mainnet and testnet addresses
homepage: https://github.com/dspicher/btc_address_validate

dependencies:
    dart_bech32: ^1.0.0
    base58check: ^2.0.0
    equatable: ^2.0.3
    bech32: ^0.2.1

dev_dependencies:
    test: ^1.23.1
    lints: ^1.0.1

environment:
    sdk: ">=2.19.0-0 <3.0.0"
